config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'teams#index'
  resources :teams do
  
    resources :members do
      collection do
        get "player"
      end
      collection do
        get "team"
      end
    end
    resources :defences
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/catcher_field.rb
class CatcherField < ApplicationRecord
end

app/models/center_field.rb
class CenterField < ApplicationRecord
end

app/models/defence.rb
class Defence < ApplicationRecord
  belongs_to :user
  has_many :members

  validates :pitcher_id, :catcher_id, :first_id, :second_id, :third_id, :short_id, :left_id, :center_id, :right_id, presence: true
  validates :pitcher_id, :catcher_id, :first_id, :second_id, :third_id, :short_id, :left_id, :center_id, :right_id, numericality: { other_than: 0 }

end

app/models/first_field.rb
class FirstField < ApplicationRecord
end

app/models/hitting.rb
class Hitting < ActiveHash::Base
  self.data = [
    {id: 0, name: "選択してください"},
    {id: 1, name: "右"},
    {id: 2, name: "左"},
    {id: 3, name: "両"}

]

end

app/models/left_field.rb
class LeftField < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :school_year
  belongs_to_active_hash :throwing
  belongs_to_active_hash :hitting

  belongs_to :user
  belongs_to :defence

  has_one_attached :image
end

app/models/pitcher_field.rb
class PitcherField < ApplicationRecord
end

app/models/right_field.rb
class RightField < ApplicationRecord
end

app/models/school_year.rb
class SchoolYear < ActiveHash::Base
  self.data = [
    {id: 0, name: "選択してください"},
    {id: 1, name: "１年生"},
    {id: 2, name: "２年生"},
    {id: 3, name: "３年生"},
    {id: 4, name: "４年生"},
    {id: 5, name: "５年生"},
    {id: 6, name: "６年生"}
]

end

app/models/second_field.rb
class SecondField < ApplicationRecord
end

app/models/short_field.rb
class ShortField < ApplicationRecord
end

app/models/third_field.rb
class ThirdField < ApplicationRecord
end

app/models/throwing.rb
class Throwing < ActiveHash::Base
  self.data = [
    {id: 0, name: "選択してください"},
    {id: 1, name: "右"},
    {id: 2, name: "左"}
  ]
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :members
  has_many :defences
  # has_many :defences
end

app/controllers/defences_controller.rb
class DefencesController < ApplicationController
  before_action :authenticate_user!, only: [:index]


  def index
    @defence = Defence.all

  end

  def new
    @defence = Defence.new
    @members = Member.all

  end

  def create
    # binding.pry
    @defence = Defence.new(defence_params)
    if @defence.save
      redirect_to root_path
    else
      render 'index'
    end
  end

  def edit
    @defence = Defence.find(params[:id])
  end

  def show
    @defence = Defence.all
  end



  private
  def defence_params
    params.require(:defence).permit(:match_name, :date, :pitcher_id, :catcher_id, :first_id, :second_id, :third_id, :short_id, :left_id, :center_id, :right_id).merge(user_id: current_user.id)
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :move_to_new_user_session, except: [:index]    

  def index
    @users = User.all
    # @members = Member.all
    # @defenses = Defence.all
  end

  def new
    @member = Member.new
  end

  def create
    # binding.pry
    @member = Member.new(member_params)
    if @member.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def player
    @members = Member.all
  end

  def team
    @users  = User.all
  end

  def show
    @users  = User.all

    # @member = Member.find(params[:id])
  end

  def edit
    @users = User.find(params[:id])
    
  end

  def update
    # binding.pry
    @users = User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to root_path
    else
      render 'show'
    end


  end

  private
  def member_params
    params.require(:user).permit(:name, :director, :email, :encrypted_password, :group, :tell)
  end

  def move_to_new_user_session
    redirect_to new_user_session_path unless user_signed_in?   
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/defences/edit.html.erb
<%= render "shared/header" %>

<div class="offence-main-wrap">
  <div class="offence-side-wrap">
  </div>
  <table class="offence-members">
    <tr>
      <th class="batting-order">打順</th>　
      <th class="start-order-names">選手名</th>
    　<th class="positioning">守</th>
    　<th class="throwing">投</th>
    　<th class="batting">打</th>
      <th class="order-school-year">学年</th>
    </tr>

    <tr>
      <td>１</td>
      <td>hoge</td>
      <td>遊</td>
      <td>右</td>
      <td>左</td>
      <td>３</td>
    </tr>
    <tr>
      <td>２</td>
      <td>hoge</td>
      <td>遊</td>
      <td>右</td>
      <td>左</td>
    　<td>３</td>
    </tr>
    <tr>
      <td>３</td>
      <td>hoge</td>
      <td>遊</td>
      <td>右</td>
      <td>左</td>
      <td>３</td>
    </tr>
    <tr>
      <td>4</td>
      <td>hoge</td>
      <td>遊</td>
      <td>右</td>
      <td>左</td>
      <td>３</td>
    </tr>
    <tr>
      <td>5</td>
      <td>hoge</td>
      <td>遊</td>
      <td>右</td>
      <td>左</td>
      <td>3</td>
    </tr>
    <tr>
      <td>6</td>
      <td>hoge</td>
      <td>遊</td>
      <td>右</td>
      <td>左</td>
      <td>3</td>
    </tr>
    <tr>
      <td>7</td>
      <td>hoge</td>
      <td>遊</td>
      <td>右</td>
      <td>左</td>
      <td>3</td>
    </tr>
    <tr>
      <td>8</td>
      <td>hoge</td>
      <td>遊</td>
      <td>右</td>
      <td>左</td>
      <td>3</td>
    </tr>
    <tr>
      <td>9</td>
      <td>hoge</td>
      <td>遊</td>
      <td>右</td>
      <td>左</td>
      <td>3</td>
    </tr>
  </table>
  <div class="charge-send-wrap">
    <div class="member-change-wrap">
      <input type="submit" value="Change" class="member-change-btn">
    </div>
    <div class="offence-set-wrap">
      <input type="submit" value="保存する" class="order-create-btn">
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/defences/index.html.erb
<%= render "shared/header" %>

<div class="defence-main-wrap">
  <div class="defence-wrap">
    <ul class="defence-menu-lists">
      <%# <li><%= link_to "マイページ", "#", class:"memu-list" %></li>         %>
      <%# <li><%= link_to "選手登録", new_member_path, class:"memu-list" %></li> %>
      <%# <li><%= link_to "選手一覧", player_members_path, class:"memu-list" %></li> %>
      <li><%= link_to "スタメン設定", new_team_defence_path, class:"memu-list" %></li>
      <%# <li><%= link_to "スタメン設定", new_defence_path, class:"memu-list" %></li> %>

    </ul>
  </div>
</div>

<%= render "shared/footer" %>

app/views/defences/new.html.erb
<%= render "shared/header" %>
<%= form_with model: @defence, url: team_defences_path, class: "defence-main-wrap", local: true do |f| %>
<div class="offence-main-wrap">
  <div class="match-form-group">
    <div class='match-form-text-wrap'>
      <%= current_user.name %>
      <label class="form-text">VS</label>
      <%= f.text_field :match_name, class:"main-match-name", id:"nickname", placeholder:"例) furima太郎", maxlength:"40" %>
      <%# <%= f.date_select :date %> %>
    </div>
  </div>
    
  <div class="offence-wrap">
    <table class="offence-members">
      <tr>
        <th class="batting-order">打順</th>　
        <th class="start-order-names">選手名</th>
      　<th class="positioning">守</th>
      </tr>
      <tr>
        <td>１</td>
        <td><%= f.collection_select(:pitcher_id, Member.all, :id, :name, {prompt:"選択してください"}, {class:"member-select"})%></td>
        <td>右</td>
      </tr>
      <tr>
        <td>２</td>
        <td><%= f.collection_select(:catcher_id, Member.all, :id, :name, {prompt:"選択してください"}, {class:"member-select"})%></td>
        <td>遊</td>
      </tr>
      <tr>
        <td>３</td>
        <td><%= f.collection_select(:first_id, Member.all, :id, :name, {prompt:"選択してください"}, {class:"member-select"})%></td>
        <td>遊</td>
      </tr>
      <tr>
        <td>4</td>
        <td><%= f.collection_select(:second_id, Member.all, :id, :name, {prompt:"選択してください"}, {class:"member-select"})%></td>
        <td>遊</td>
      </tr>
      <tr>
        <td>5</td>
        <td><%= f.collection_select(:third_id, Member.all, :id, :name, {prompt:"選択してください"}, {class:"member-select"})%></td>
        <td>遊</td>
      </tr>
      <tr>
        <td>6</td>
        <td><%= f.collection_select(:short_id, Member.all, :id, :name, {prompt:"選択してください"}, {class:"member-select"})%></td>
        <td>遊</td>
      </tr>
      <tr>
        <td>7</td>
        <td><%= f.collection_select(:left_id, Member.all, :id, :name, {prompt:"選択してください"}, {class:"member-select"})%></td>
        <td>遊</td>
      </tr>
      <tr>
        <td>8</td>
        <td><%= f.collection_select(:center_id, Member.all, :id, :name, {prompt:"選択してください"}, {class:"member-select"})%></td>
        <td>遊</td>
      </tr>
      <tr>
        <td>9</td>
        <td><%= f.collection_select(:right_id, Member.all, :id, :name, {prompt:"選択してください"}, {class:"member-select"})%></td>
        <td>遊</td>
      </tr>
    </table>
  </div>
  <div class="offence-set-wrap">
    <input type="submit" value="保存する" class="order-create-btn">
  </div>
</div>
<% end %>
<%= render "shared/footer" %>

app/views/defences/show.html.erb
<%= render "shared/header" %>

<div class="offence-main-wrap">
  <div class="offence-side-wrap">
  </div>
  <table class="offence-members">
    <tr>
      <th class="batting-order">打順</th>　
      <th class="start-order-names">選手名</th>
    　<th class="positioning">守</th>
    　<th class="throwing">投</th>
    　<th class="batting">打</th>
      <th class="order-school-year">学年</th>
    </tr>

    <tr>
      <td>１</td>
      <td>hoge</td>
      <td>遊</td>
      <td>右</td>
      <td>左</td>
      <td>３</td>
    </tr>
    <tr>
      <td>２</td>
      <td>hoge</td>
      <td>遊</td>
      <td>右</td>
      <td>左</td>
    　<td>３</td>
    </tr>
    <tr>
      <td>３</td>
      <td>hoge</td>
      <td>遊</td>
      <td>右</td>
      <td>左</td>
      <td>３</td>
    </tr>
    <tr>
      <td>4</td>
      <td>hoge</td>
      <td>遊</td>
      <td>右</td>
      <td>左</td>
      <td>３</td>
    </tr>
    <tr>
      <td>5</td>
      <td>hoge</td>
      <td>遊</td>
      <td>右</td>
      <td>左</td>
      <td>3</td>
    </tr>
    <tr>
      <td>6</td>
      <td>hoge</td>
      <td>遊</td>
      <td>右</td>
      <td>左</td>
      <td>3</td>
    </tr>
    <tr>
      <td>7</td>
      <td>hoge</td>
      <td>遊</td>
      <td>右</td>
      <td>左</td>
      <td>3</td>
    </tr>
    <tr>
      <td>8</td>
      <td>hoge</td>
      <td>遊</td>
      <td>右</td>
      <td>左</td>
      <td>3</td>
    </tr>
    <tr>
      <td>9</td>
      <td>hoge</td>
      <td>遊</td>
      <td>右</td>
      <td>左</td>
      <td>3</td>
    </tr>
  </table>
  <div class="charge-send-wrap">
    <div class="member-change-wrap">
      <input type="submit" value="Change" class="member-change-btn">
    </div>
    <div class="offence-set-wrap">
      <input type="submit" value="保存する" class="order-create-btn">
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/defences/sub.html.erb
<%= render "shared/header" %>
<%= form_with model: @defence,  class: "defence-main-wrap", local: true do |f| %>

  <div class="defence-main-image">
    <%= image_tag "779871.jpg", class:"defence-image" %>
    <div>
      <%= f.collection_select(:pitcher_id, Member.where("pitcher_position"), :id, :name, {prompt:"選択してください"} , {class:"pitcher-field"})%>
    </div>
    <div>
      <%= f.collection_select(:catcher_id, Member.where("catcher_position"), :id, :name, {prompt: "選択してください"}, {class:"catcher-field"}) %>
    </div>
    <div>
      <%= f.collection_select(:first_id, Member.where("first_position"), :id, :name, {prompt: "選択してください"}, {class:"first-field"}) %>
    </div>
    <div>
      <%= f.collection_select(:second_id, Member.where("second_position"), :id, :name, {prompt: "選択してください"}, {class:"second-field"}) %>
    </div>
    <div>
      <%= f.collection_select(:third_id, Member.where("third_position"), :id, :name, {prompt: "選択してください"}, {class:"third-field"}) %>
    </div>
    <div>
      <%= f.collection_select(:short_id, Member.where("short_position"), :id, :name, {prompt: "選択してください"}, {class:"short-field"}) %>
    </div>
    <div>
      <%= f.collection_select(:left_id, Member.where("outside_position"), :id, :name, {prompt: "選択してください"}, {class:"left-field"}) %>
    </div>
    <div>
      <%= f.collection_select(:center_id, Member.where("outside_position"), :id, :name, {prompt: "選択してください"}, {class:"center-field"}) %>
    </div>
    <div>
      <%= f.collection_select(:right_id, Member.where("outside_position"), :id, :name, {prompt: "選択してください"}, {class:"right-field"}) %>
    </div>
    <div class="defence-next-btn">
      <%= f.submit "打順設定へ進む", class:"defence-btn" %>
    </div>
  </div>
  
<% end %>
<%= render "shared/footer" %>