config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'teams#index'
  resources :teams do
  
    resources :members do
      collection do
        get "player"
      end
      collection do
        get "team"
      end
    end
    resources :defences
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/catcher_field.rb
class CatcherField < ApplicationRecord
end

app/models/center_field.rb
class CenterField < ApplicationRecord
end

app/models/defence.rb
class Defence < ApplicationRecord
  belongs_to :user
  has_many :members

  validates :pitcher_id, :catcher_id, :first_id, :second_id, :third_id, :short_id, :left_id, :center_id, :right_id, presence: true
  validates :pitcher_id, :catcher_id, :first_id, :second_id, :third_id, :short_id, :left_id, :center_id, :right_id, numericality: { other_than: 0 }

end

app/models/first_field.rb
class FirstField < ApplicationRecord
end

app/models/hitting.rb
class Hitting < ActiveHash::Base
  self.data = [
    {id: 0, name: "選択してください"},
    {id: 1, name: "右"},
    {id: 2, name: "左"},
    {id: 3, name: "両"}

]

end

app/models/left_field.rb
class LeftField < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :school_year
  belongs_to_active_hash :throwing
  belongs_to_active_hash :hitting

  belongs_to :user
  belongs_to :defence

  has_one_attached :image
end

app/models/pitcher_field.rb
class PitcherField < ApplicationRecord
end

app/models/right_field.rb
class RightField < ApplicationRecord
end

app/models/school_year.rb
class SchoolYear < ActiveHash::Base
  self.data = [
    {id: 0, name: "選択してください"},
    {id: 1, name: "１年生"},
    {id: 2, name: "２年生"},
    {id: 3, name: "３年生"},
    {id: 4, name: "４年生"},
    {id: 5, name: "５年生"},
    {id: 6, name: "６年生"}
]

end

app/models/second_field.rb
class SecondField < ApplicationRecord
end

app/models/short_field.rb
class ShortField < ApplicationRecord
end

app/models/third_field.rb
class ThirdField < ApplicationRecord
end

app/models/throwing.rb
class Throwing < ActiveHash::Base
  self.data = [
    {id: 0, name: "選択してください"},
    {id: 1, name: "右"},
    {id: 2, name: "左"}
  ]
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :members
  has_many :defences
  # has_many :defences
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  
  def index
    @members = Member.all
    @defenses = Defence.all
  end

  def new
    @member = Member.new
  end

  def create
    # binding.pry
    @member = Member.new(member_params)
    if @member.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def player
    @members = Member.all
  end

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
    
  end

  def update
    # binding.pry
    @member = Member.find(params[:id])
    if @member.update(member_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @member = Member.find(params[:id])
    if @member.destroy
      redirect_to root_path
    else
      render 'show'
    end


  end

  private
  def member_params
    params.require(:member).permit(:image, :name, :school_year_id, :age, :tall, :weight, :throwing_id, :hitting_id, :number, :pitcher_position, :catcher_position, :first_position, :second_position, :third_position, :short_position, :outside_position).merge(user_id: current_user.id)
  end


end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :move_to_new_user_session, except: [:index]    

  def index
    @users = User.all
    # @members = Member.all
    # @defenses = Defence.all
  end

  def new
    @member = Member.new
  end

  def create
    # binding.pry
    @member = Member.new(member_params)
    if @member.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def player
    @members = Member.all
  end

  def team
    @users  = User.all
  end

  def show
    @users  = User.all

    # @member = Member.find(params[:id])
  end

  def edit
    @users = User.find(params[:id])
    
  end

  def update
    # binding.pry
    @users = User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to root_path
    else
      render 'show'
    end


  end

  private
  def member_params
    params.require(:user).permit(:name, :director, :email, :encrypted_password, :group, :tell)
  end

  def move_to_new_user_session
    redirect_to new_user_session_path unless user_signed_in?   
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/members/edit.html.erb
<%= render "shared/header" %>

<%= form_with model: @member, class:"registration", local: true do |f| %>
  <div class="main-registration-contents">

    <div class="form-wrap">
      <div class="form-header-text">
        選手情報編集
      </div>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">選手画像</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.file_field :image, class:"small-field", id:"member_image" %>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">名前</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :name, placeholder:"山田　太郎", class:"small-field", id:"member_name" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">学年</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:school_year_id, SchoolYear.all, :id, :name, {}, {class:"small-field", id:"member_school_year"}) %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">年齢</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :age, placeholder:"半角数字を入力してください", class:"small-field"%> 
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">身長</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :tall, placeholder:"半角数字を入力してください", class:"small-field" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">体重</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :weight, placeholder:"半角数字を入力してください", class:"small-field" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">投球</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:throwing_id, Throwing.all, :id, :name, {}, {class:"small-field", id:"member_throwing"}) %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">打席</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:hitting_id, Hitting.all, :id, :name, {}, {class:"small-field", id:"member_hitting"}) %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">背番号</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :number, placeholder:"半角数字を入力してください", class:"small-field" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">投手</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.check_box :pitcher_position %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">捕手</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.check_box :catcher_position %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">一塁手</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.check_box :first_position %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">二塁手</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.check_box :second_position %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">三塁手</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.check_box :third_position %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">遊撃手</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.check_box :short_position %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">外野手</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.check_box :outside_position %>
    </div>

    <div class='register-btn'>
      <%= f.submit "変更する", class:"register-send" %>
    </div>

  </div>
<% end %>
<%= render "shared/footer" %>

app/views/members/index.html.erb
<%= render "shared/header" %>
<div class="main-page">
  <div class="first-view">
    <div class="top-image-content">
      <ul class="main-menu-lists">
        <%# <li><%= link_to "マイページ", team_path, class:"memu-list"%></li>          %>
        <li><%= link_to "選手登録", new_team_member_path, class:"memu-list" %></li>
        <%# <li><%= link_to "選手一覧", team_members_path, class:"memu-list" %></li> %>
        <li><%= link_to "スタメン", team_defences_path, class:"memu-list" %></li>
      </ul>
    </div> 
    <div class="registration">
      <div class="member-contents-wrap">
        <div class="member-header">
          <p>選手一覧</p>
        </div>
        <ul class="position-lists">
          <li class="position-list">
            投手
          </li>
          <li class="position-list">
            捕手
          </li>
          <li class="position-list">
            内野手
          </li>
          <li class="position-list">
            外野手
          </li>
        </ul>
          <ul class="member-contents">
            <% @members.each do |member| %>
              <li class="member-content">
                <%= link_to member_path(member.id) do %>
                <%= image_tag member.image.variant(resize:'500x500'), class:"member-image" if member.image.attached? %>
                <div class="member-name"><%= member.name %></div>
                <% end %>
              </li>
            <% end %>
          </ul>
      </div>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/members/new.html.erb
<%= render "shared/header" %>

<%= form_with model: @member, url: team_members_path, class:"registration", local: true do |f| %>
  <div class="main-registration-contents">
    <div class="form-wrap">
      <div class="form-header-text">
        選手情報入力
      </div>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">選手画像</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.file_field :image, class:"small-field", id:"member_image" %>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">名前</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :name, placeholder:"山田　太郎", class:"small-field", id:"member_name" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">学年</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:school_year_id, SchoolYear.all, :id, :name, {}, {class:"small-field", id:"member_school_year"}) %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">年齢</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :age, placeholder:"半角数字を入力してください", class:"small-field"%> 
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">身長</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :tall, placeholder:"半角数字を入力してください", class:"small-field" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">体重</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :weight, placeholder:"半角数字を入力してください", class:"small-field" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">投球</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:throwing_id, Throwing.all, :id, :name, {}, {class:"small-field", id:"member_throwing"}) %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">打席</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:hitting_id, Hitting.all, :id, :name, {}, {class:"small-field", id:"member_hitting"}) %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">背番号</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :number, placeholder:"半角数字を入力してください", class:"small-field" %>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">投手</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.check_box :pitcher_position %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">捕手</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.check_box :catcher_position %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">一塁手</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.check_box :first_position %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">二塁手</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.check_box :second_position %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">三塁手</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.check_box :third_position %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">遊撃手</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.check_box :short_position %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">外野手</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.check_box :outside_position %>
    </div>
    <div class='register-btn'>
      <%= f.submit "選手登録", class:"register-send" %>
    </div>

  </div>
<% end %>
<%= render "shared/footer" %>

app/views/members/player.html.erb
<%= render "shared/header" %>

<div class="registration">
  <div class="member-contents-wrap">
    <div class="member-header">
      <p>選手一覧</p>
    </div>
    <ul class="position-lists">
      <li class="position-list">
        投手
      </li>
      <li class="position-list">
        捕手
      </li>
      <li class="position-list">
        内野手
      </li>
      <li class="position-list">
        外野手
      </li>
    </ul>
      <ul class="member-contents">
        <% @members.each do |member| %>
          <li class="member-content">
            <%= link_to member_path(member.id) do %>
            <%= image_tag member.image.variant(resize:'500x500'), class:"member-image" if member.image.attached? %>
            <div class="member-name"><%= member.name %></div>
            <% end %>
          </li>
        <% end %>
      </ul>
  </div>
</div>
<%= render "shared/footer" %>

app/views/members/show.html.erb
<%= render "shared/header" %>

<div class="registration">
  <div class="member-contents-wrap">
    <div class="member-header">
      <p>選手詳細</p>
    </div>
    <div class="member-only-content">

      <div class="member-only-image">
        <%= image_tag @member.image, class:"only-image" %>
        <div class="only-data-content">
          <div class="only-data-list">
            <p>名前：</p>
          </div>
          <div class="only-data-name">
            <p><%= @member.name %></p>
          </div>
        </div>
        <div class="only-data-content">
          <div class="only-data-list">
            <p>学年：</p>
          </div>
          <div class="only-data-name">
            <p><%= @member.school_year.name %></p>
          </div>
        </div>
        <div class="only-data-content">
          <div class="only-data-list">
            <p>背番号：</p>
          </div>
          <div class="only-data-name">
            <p><%= @member.number %></p>
          </div>
        </div>


      </div>


      <div class="member-only-data-contents">

        <div class="only-data-content">
          <div class="only-data-list">
            <p>守備位置：</p>
          </div>
          <div class="only-data-name">
          <% if @member.pitcher_position %>
            <p>投手</p>
          <% end %>
          </div>
        </div>
        <div class="only-data-content">
          <div class="only-data-list">
            <p>守備位置：</p>
          </div>
          <div class="only-data-name">
          <% if @member.catcher_position %>
            <p>捕手</p>
          <% end %>
          </div>
        </div>
        <div class="only-data-content">
          <div class="only-data-list">
            <p>守備位置：</p>
          </div>
          <div class="only-data-name">
          <% if @member.first_position %>
            <p>一塁手</p>
          <% end %>
          </div>
        </div>
        <div class="only-data-content">
          <div class="only-data-list">
            <p>守備位置：</p>
          </div>
          <div class="only-data-name">
          <% if @member.second_position %>
            <p>二塁手</p>
          <% end %>
          </div>
        </div>
        <div class="only-data-content">
          <div class="only-data-list">
            <p>守備位置：</p>
          </div>
          <div class="only-data-name">
          <% if @member.third_position %>
            <p>三塁手</p>
          <% end %>
          </div>
        </div>
        <div class="only-data-content">
          <div class="only-data-list">
            <p>守備位置：</p>
          </div>
          <div class="only-data-name">
          <% if @member.short_position %>
            <p>遊撃手</p>
          <% end %>
          </div>
        </div>
        <div class="only-data-content">
          <div class="only-data-list">
            <p>守備位置：</p>
          </div>
          <div class="only-data-name">
          <% if @member.outside_position %>
            <p>外野手</p>
          <% end %>
          </div>
        </div>
        <div class="only-data-content">
          <div class="only-data-list">
            <p>身長：</p>
          </div>
          <div class="only-data-name">
            <p><%= @member.tall %></p>
          </div>
        </div>

        <div class="only-data-content">
          <div class="only-data-list">
            <p>体重：</p>
          </div>
          <div class="only-data-name">
            <p><%= @member.weight %></p>
          </div>
        </div>

        <div class="only-data-content">
          <div class="only-data-list">
            <p>投球：</p>
          </div>
          <div class="only-data-name">
            <p><%= @member.throwing.name %></p>
          </div>
        </div>

        <div class="only-data-content">
          <div class="only-data-list">
            <p>打席：</p>
          </div>
          <div class="only-data-name">
            <p><%= @member.hitting.name %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="member-only-edit">
      <%= link_to "編集", edit_member_path, method: :get, class:"member-only-edit-btn" %>
      <%= link_to "削除", member_path, method: :delete, class:"member-only-edit-btn" %>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/members/team.html.erb
<%= render "shared/header" %>

<div class="registration">
  <div class="team-contents-wrap">
    <div class="member-header">
      <p>チーム情報</p>
    </div>
    <div class="team-contents">
      <% @users.each do |user| %>
        <div class="only-data-content">
          <div class="team-data-list">
            <p>名前：</p>
          </div>
          <div class="team-data-name">
            <p><%= user.name %></p>
          </div>
        </div>
        <div class="only-data-content">
          <div class="team-data-list">
            <p>監督：</p>
          </div>
          <div class="team-data-name">
            <p><%= user.director %></p>
          </div>
        </div>
        <div class="only-data-content">
          <div class="team-data-list">
            <p>メールアドレス：</p>
          </div>
          <div class="team-data-name">
            <p><%= user.email %></p>
          </div>
        </div>
        <div class="only-data-content">
          <div class="team-data-list">
            <p>属性：</p>
          </div>
          <div class="team-data-name">
            <p><%= user.group %></p>
          </div>
        </div>
        <div class="only-data-content">
          <div class="team-data-list">
            <p>電話番号：</p>
          </div>
          <div class="team-data-name">
            <p><%= user.tell %></p>
          </div>
        </div>

        <% end %>
        <div class="team-edit">
          <%= link_to "編集", "#", method: :get, class:"team-only-edit-btn" %>
          <%= link_to "削除", "#", method: :delete, class:"team-only-edit-btn" %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render "shared/footer" %>